from datetime import datetime, timezone
from typing import Optional, List, Dict
import uuid

from sqlmodel import SQLModel, Field, Relationship
from sqlalchemy import Column, UniqueConstraint, Index, CheckConstraint, text
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.types import DateTime


# =========================
# Utilidades y constantes
# =========================

def now_utc() -> datetime:
    return datetime.now(timezone.utc)


AUTH_TABLE_ARGS = {"schema": "auth"}


# =========================
#  SCHEMA auth : Users
# =========================

class Users(SQLModel, table=True):
    """
    auth.users
    - id: uuid autogenerated primary key
    - full_name: str
    - email: unique not null
    - profile_pic: unique
    """
    __tablename__ = "users"
    __table_args__ = (AUTH_TABLE_ARGS,)

    id: uuid.UUID = Field(
        default_factory=uuid.uuid4,
        primary_key=True,
        sa_column_kwargs={"server_default": text("gen_random_uuid()")},
    )
    full_name: str = Field(nullable=True, index=True)
    email: str = Field(nullable=False, unique=True, index=True)
    password_hash: str = Field(nullable=False)
    phone: Optional[str] = Field(default=None, unique=True)
    profile_pic: Optional[str] = Field(default=None, unique=True)
    role: str = Field(nullable=False, index=True)

    email_verified_at: Optional[datetime] = Field(
        default=None,
        sa_column=Column(DateTime(timezone=True), nullable=True, index=True)
    )
    created_at: datetime = Field(
        default_factory=now_utc,
        sa_column=Column(DateTime(timezone=True), nullable=False, index=True, server_default=text("CURRENT_TIMESTAMP"))
    )
    updated_at: datetime = Field(
        default_factory=now_utc,
        sa_column=Column(DateTime(timezone=True), nullable=False, index=True, server_default=text("CURRENT_TIMESTAMP"))
    )

    manager: Optional["Manager"] = Relationship(back_populates="user")
    crew: Optional["Crew"] = Relationship(back_populates="user")
    driver: Optional["Driver"] = Relationship(back_populates="user")

    sent_messages: List["Message"] = Relationship(
        back_populates="sender",
        sa_relationship_kwargs={
            "foreign_keys": "[Message.sender_id]",
            "cascade": "all, delete-orphan",
        },
    )
    received_messages: List["Message"] = Relationship(
        back_populates="recipient",
        sa_relationship_kwargs={
            "foreign_keys": "[Message.recipient_id]",
            "cascade": "all, delete-orphan",
        },
    )
    notifications_received: List["Notification"] = Relationship(
        back_populates="recipient",
        sa_relationship_kwargs={
            "foreign_keys": "[Notification.recipient_id]",
            "cascade": "all, delete-orphan",
        },
    )
    refresh_tokens: List["RefreshToken"] = Relationship(
        back_populates="user",
        sa_relationship_kwargs={"cascade": "all, delete-orphan"},
    )


# =========================================
#  SCHEMA public : Manager, Crew, Driver
# =========================================

class Manager(SQLModel, table=True):
    """
    public.manager  (subtipo de Users)
    """
    __tablename__ = "manager"

    id: uuid.UUID = Field(primary_key=True, foreign_key="auth.users.id", nullable=False)
    organization_id: Optional[uuid.UUID] = Field(
        default=None, foreign_key="organization.id", index=True
    )

    user: Users = Relationship(back_populates="manager")

    organization: Optional["Organization"] = Relationship(
        back_populates="managers",
        sa_relationship_kwargs={"foreign_keys": "[Manager.organization_id]"},
    )


class Crew(SQLModel, table=True):
    """
    public.crew  (subtipo de Users)
    """
    __tablename__ = "crew"

    id: uuid.UUID = Field(primary_key=True, foreign_key="auth.users.id", nullable=False)
    aeroline: Optional[str] = Field(
        default=None,
        description="Código AA, WN, DL...",
        index=True,
    )

    user: Users = Relationship(back_populates="crew")


class Driver(SQLModel, table=True):
    """
    public.driver  (subtipo de Users)
    """
    __tablename__ = "driver"

    id: uuid.UUID = Field(primary_key=True, foreign_key="auth.users.id", nullable=False)
    is_active: bool = Field(default=True, nullable=False, index=True)
    point: Optional[str] = Field(default=None)
    location_id: Optional[uuid.UUID] = Field(
        default=None, foreign_key="location.id", index=True
    )

    user: Users = Relationship(back_populates="driver")
    location: Optional["Location"] = Relationship(back_populates="drivers")
    trips: List["Trip"] = Relationship(back_populates="driver")


# =========================
#  SCHEMA public : Domain
# =========================

class Organization(SQLModel, table=True):
    """
    public.organization
    """
    __tablename__ = "organization"
    __table_args__ = (
        UniqueConstraint("name", name="uq_organization_name"),
    )

    id: uuid.UUID = Field(
        default_factory=uuid.uuid4,
        primary_key=True,
        sa_column_kwargs={"server_default": text("gen_random_uuid()")},
    )
    name: str = Field(nullable=False, index=True, unique=True)

    manager_id: Optional[uuid.UUID] = Field(
        default=None, foreign_key="manager.id", index=True
    )

    email: Optional[str] = Field(default=None)
    phone: str = Field(nullable=False)

    plan: str = Field(default="freemium", nullable=False, index=True)
    status: Optional[str] = Field(default=None, index=True)

    created_at: datetime = Field(
        default_factory=now_utc,
        sa_column=Column(DateTime(timezone=True), nullable=False, index=True, server_default=text("CURRENT_TIMESTAMP"))
    )
    updated_at: datetime = Field(
        default_factory=now_utc,
        sa_column=Column(DateTime(timezone=True), nullable=False, index=True, server_default=text("CURRENT_TIMESTAMP"))
    )

    managers: List["Manager"] = Relationship(
        back_populates="organization",
        sa_relationship_kwargs={"foreign_keys": "[Manager.organization_id]"},
    )

    primary_manager: Optional["Manager"] = Relationship(
        sa_relationship_kwargs={"foreign_keys": "[Organization.manager_id]"},
    )

    locations: List["Location"] = Relationship(back_populates="organization")


class Location(SQLModel, table=True):
    """
    public.location
    """
    __tablename__ = "location"

    id: uuid.UUID = Field(
        default_factory=uuid.uuid4,
        primary_key=True,
        sa_column_kwargs={"server_default": text("gen_random_uuid()")},
    )
    organization_id: uuid.UUID = Field(
        foreign_key="organization.id", nullable=False, index=True
    )
    name: str = Field(nullable=False, index=True)
    point: Optional[str] = Field(default=None)

    organization: "Organization" = Relationship(back_populates="locations")

    drivers: List["Driver"] = Relationship(back_populates="location")
    trips: List["Trip"] = Relationship(back_populates="location")


class Trip(SQLModel, table=True):
    """
    public.trip
    """
    __tablename__ = "trip"

    id: uuid.UUID = Field(
        default_factory=uuid.uuid4,
        primary_key=True,
        sa_column_kwargs={"server_default": text("gen_random_uuid()")},
    )
    assigned_driver: Optional[uuid.UUID] = Field(
        default=None, foreign_key="driver.id", index=True
    )
    location_id: uuid.UUID = Field(
        foreign_key="location.id", nullable=False, index=True
    )

    pick_up_time: datetime = Field(
        sa_column=Column(DateTime(timezone=True), nullable=False, index=True)  # ✅ SIN nullable en Field
    )
    pick_up_location: str = Field(nullable=False)
    drop_off_location: str = Field(nullable=False)
    aeroline: str = Field(nullable=False, index=True)

    riders: Dict[str, int] = Field(
        sa_column=Column(JSONB, nullable=False, server_default=text("'{}'::jsonb"))
    )

    started_at: Optional[datetime] = Field(
        default=None,
        sa_column=Column(DateTime(timezone=True), nullable=True, index=True)
    )
    picked_up_at: Optional[datetime] = Field(
        default=None,
        sa_column=Column(DateTime(timezone=True), nullable=True, index=True)
    )
    dropped_off_at: Optional[datetime] = Field(
        default=None,
        sa_column=Column(DateTime(timezone=True), nullable=True, index=True)
    )

    created_at: datetime = Field(
        default_factory=now_utc,
        sa_column=Column(DateTime(timezone=True), nullable=False, index=True, server_default=text("CURRENT_TIMESTAMP"))
    )
    updated_at: datetime = Field(
        default_factory=now_utc,
        sa_column=Column(DateTime(timezone=True), nullable=False, index=True, server_default=text("CURRENT_TIMESTAMP"))
    )

    driver: Optional["Driver"] = Relationship(back_populates="trips")
    location: "Location" = Relationship(back_populates="trips")


class TripHistory(SQLModel, table=True):
    """
    public.trip_history
    """
    __tablename__ = "trip_history"

    id: uuid.UUID = Field(
        default_factory=uuid.uuid4,
        primary_key=True,
        sa_column_kwargs={"server_default": text("gen_random_uuid()")},
    )
    assigned_driver: Optional[uuid.UUID] = Field(
        default=None, foreign_key="driver.id", index=True
    )
    location_id: uuid.UUID = Field(
        foreign_key="location.id", nullable=False, index=True
    )

    pick_up_time: datetime = Field(
        sa_column=Column(DateTime(timezone=True), nullable=False, index=True)
    )
    pick_up_location: str = Field(nullable=False)
    drop_off_location: str = Field(nullable=False)
    aeroline: str = Field(nullable=False, index=True)

    riders: Dict[str, int] = Field(
        sa_column=Column(JSONB, nullable=False, server_default=text("'{}'::jsonb"))
    )

    started_at: Optional[datetime] = Field(
        default=None,
        sa_column=Column(DateTime(timezone=True), nullable=True, index=True)
    )
    picked_up_at: Optional[datetime] = Field(
        default=None,
        sa_column=Column(DateTime(timezone=True), nullable=True, index=True)
    )
    dropped_off_at: Optional[datetime] = Field(
        default=None,
        sa_column=Column(DateTime(timezone=True), nullable=True, index=True)
    )

    created_at: datetime = Field(
        default_factory=now_utc,
        sa_column=Column(DateTime(timezone=True), nullable=False, index=True, server_default=text("CURRENT_TIMESTAMP"))
    )
    updated_at: datetime = Field(
        default_factory=now_utc,
        sa_column=Column(DateTime(timezone=True), nullable=False, index=True, server_default=text("CURRENT_TIMESTAMP"))
    )


# ======================================
#  SCHEMA public : Notification
# ======================================

class Notification(SQLModel, table=True):
    """
    public.notification
    """
    __tablename__ = "notification"

    id: uuid.UUID = Field(
        default_factory=uuid.uuid4,
        primary_key=True,
        sa_column_kwargs={"server_default": text("gen_random_uuid()")},
    )

    sender_label: Optional[str] = Field(default="system", index=True)
    sender_id: Optional[uuid.UUID] = Field(
        default=None, foreign_key="auth.users.id", index=True
    )

    recipient_id: uuid.UUID = Field(
        foreign_key="auth.users.id", nullable=False, index=True
    )

    link: Optional[str] = Field(default=None)
    created_at: datetime = Field(
        default_factory=now_utc,
        sa_column=Column(DateTime(timezone=True), nullable=False, index=True, server_default=text("CURRENT_TIMESTAMP"))
    )
    delivered_at: Optional[datetime] = Field(
        default=None,
        sa_column=Column(DateTime(timezone=True), nullable=True, index=True)
    )

    recipient: Users = Relationship(
        back_populates="notifications_received",
        sa_relationship_kwargs={"foreign_keys": "[Notification.recipient_id]"},
    )


# ======================================
#  SCHEMA public : Chat & Messages
# ======================================

class Chat(SQLModel, table=True):
    """
    public.chat
    """
    __tablename__ = "chat"

    id: uuid.UUID = Field(
        default_factory=uuid.uuid4,
        primary_key=True,
        sa_column_kwargs={"server_default": text("gen_random_uuid()")},
    )
    created_at: datetime = Field(
        default_factory=now_utc,
        sa_column=Column(DateTime(timezone=True), nullable=False, index=True, server_default=text("CURRENT_TIMESTAMP"))
    )

    participants: List["ChatParticipant"] = Relationship(
        back_populates="chat",
        sa_relationship_kwargs={"cascade": "all, delete-orphan"},
    )
    messages: List["Message"] = Relationship(
        back_populates="chat",
        sa_relationship_kwargs={"cascade": "all, delete-orphan"},
    )


class ChatParticipant(SQLModel, table=True):
    """
    public.chat_participant
    """
    __tablename__ = "chat_participant"
    __table_args__ = (
        UniqueConstraint("chat_id", "user_id", name="uq_chat_participant_unique"),
    )

    id: uuid.UUID = Field(
        default_factory=uuid.uuid4,
        primary_key=True,
        sa_column_kwargs={"server_default": text("gen_random_uuid()")},
    )
    chat_id: uuid.UUID = Field(
        foreign_key="chat.id", nullable=False, index=True
    )
    user_id: uuid.UUID = Field(
        foreign_key="auth.users.id", nullable=False, index=True
    )
    joined_at: datetime = Field(
        default_factory=now_utc,
        sa_column=Column(DateTime(timezone=True), nullable=False, index=True, server_default=text("CURRENT_TIMESTAMP"))
    )

    chat: Chat = Relationship(back_populates="participants")
    user: Users = Relationship()


class Message(SQLModel, table=True):
    """
    public.message
    """
    __tablename__ = "message"

    id: uuid.UUID = Field(
        default_factory=uuid.uuid4,
        primary_key=True,
        sa_column_kwargs={"server_default": text("gen_random_uuid()")},
    )
    chat_id: uuid.UUID = Field(
        foreign_key="chat.id", nullable=False, index=True
    )

    sender_id: uuid.UUID = Field(
        foreign_key="auth.users.id", nullable=False, index=True
    )
    recipient_id: Optional[uuid.UUID] = Field(
        default=None, foreign_key="auth.users.id", index=True
    )

    content: str = Field(nullable=False)
    created_at: datetime = Field(
        default_factory=now_utc,
        sa_column=Column(DateTime(timezone=True), nullable=False, index=True, server_default=text("CURRENT_TIMESTAMP"))
    )

    chat: Chat = Relationship(back_populates="messages")
    sender: Users = Relationship(
        back_populates="sent_messages",
        sa_relationship_kwargs={"foreign_keys": "[Message.sender_id]"},
    )
    recipient: Optional[Users] = Relationship(
        back_populates="received_messages",
        sa_relationship_kwargs={"foreign_keys": "[Message.recipient_id]"},
    )


# ======================================
#  SCHEMA auth : RefreshToken
# ======================================

class RefreshToken(SQLModel, table=True):
    """
    auth.refresh_token
    """
    __tablename__ = "refresh_token"
    __table_args__ = (
        UniqueConstraint("token_hash", name="uq_refresh_token_hash"),
        AUTH_TABLE_ARGS,
    )

    id: uuid.UUID = Field(
        default_factory=uuid.uuid4,
        primary_key=True,
        sa_column_kwargs={"server_default": text("gen_random_uuid()")},
    )
    user_id: uuid.UUID = Field(
        foreign_key="auth.users.id", nullable=False, index=True
    )
    token_hash: str = Field(nullable=False)
    expires_at: datetime = Field(
        sa_column=Column(DateTime(timezone=True), nullable=False, index=True)
    )
    revoked: bool = Field(default=False, nullable=False, index=True)
    created_at: datetime = Field(
        default_factory=now_utc,
        sa_column=Column(DateTime(timezone=True), nullable=False, index=True, server_default=text("CURRENT_TIMESTAMP"))
    )

    user: Users = Relationship(
        back_populates="refresh_tokens",
        sa_relationship_kwargs={"foreign_keys": "[RefreshToken.user_id]"},
    )
