from datetime import datetime, timezone, date, time
from typing import Optional, List, Dict
import uuid

from sqlmodel import SQLModel, Field, Relationship
from sqlalchemy import Column, UniqueConstraint, Index, CheckConstraint, text, ForeignKey  # <-- agregado
from sqlalchemy.dialects.postgresql import JSONB, UUID as PG_UUID  # <-- agregado
from sqlalchemy.types import DateTime, Date, Time, String, Float, Integer


# =========================
# Utilidades y constantes
# =========================

def now_utc() -> datetime:
    return datetime.now(timezone.utc)


AUTH_TABLE_ARGS = {"schema": "auth"}


# =========================
#  SCHEMA auth : Users
# =========================

class Users(SQLModel, table=True):
    """
    auth.users
    - id: uuid autogenerated primary key
    - full_name: str
    - email: unique not null
    - profile_pic: unique
    """
    __tablename__ = "users"
    __table_args__ = (AUTH_TABLE_ARGS,)

    id: uuid.UUID = Field(
        default_factory=uuid.uuid4,
        primary_key=True,
        sa_column_kwargs={"server_default": text("gen_random_uuid()")},
    )
    full_name: str = Field(nullable=True, index=True)
    email: str = Field(nullable=False, unique=True, index=True)
    password_hash: str = Field(nullable=False)
    phone: Optional[str] = Field(default=None, unique=True)
    profile_pic: Optional[str] = Field(default=None, unique=True)
    role: str = Field(nullable=False, index=True)

    email_verified_at: Optional[datetime] = Field(
        default=None,
        sa_column=Column(DateTime(timezone=True), nullable=True, index=True)
    )
    created_at: datetime = Field(
        default_factory=now_utc,
        sa_column=Column(DateTime(timezone=True), nullable=False, index=True, server_default=text("CURRENT_TIMESTAMP"))
    )
    updated_at: datetime = Field(
        default_factory=now_utc,
        sa_column=Column(DateTime(timezone=True), nullable=False, index=True, server_default=text("CURRENT_TIMESTAMP"))
    )

    password_reset_nonce: str | None = Field(default=None, index=True)

    manager: Optional["Manager"] = Relationship(
        back_populates="user",
        sa_relationship_kwargs={"cascade": "all, delete-orphan", "passive_deletes": True},  # <-- cascade
    )
    crew: Optional["Crew"] = Relationship(
        back_populates="user",
        sa_relationship_kwargs={"cascade": "all, delete-orphan", "passive_deletes": True},  # <-- cascade
    )
    driver: Optional["Driver"] = Relationship(
        back_populates="user",
        sa_relationship_kwargs={"cascade": "all, delete-orphan", "passive_deletes": True},  # <-- cascade
    )

    sent_messages: List["Message"] = Relationship(
        back_populates="sender",
        sa_relationship_kwargs={
            "foreign_keys": "[Message.sender_id]",
            "cascade": "all, delete-orphan",
            "passive_deletes": True,  # <-- agregado
        },
    )
    received_messages: List["Message"] = Relationship(
        back_populates="recipient",
        sa_relationship_kwargs={
            "foreign_keys": "[Message.recipient_id]",
            "cascade": "all, delete-orphan",
            "passive_deletes": True,  # <-- agregado
        },
    )
    notifications_received: List["Notification"] = Relationship(
        back_populates="recipient",
        sa_relationship_kwargs={
            "foreign_keys": "[Notification.recipient_id]",
            "cascade": "all, delete-orphan",
            "passive_deletes": True,  # <-- agregado
        },
    )
    refresh_tokens: List["Token"] = Relationship(
        back_populates="user",
        sa_relationship_kwargs={
            "cascade": "all, delete-orphan",
            "passive_deletes": True,  # <-- agregado
        },
    )


# =========================================
#  SCHEMA public : Manager, Crew, Driver
# =========================================

class Manager(SQLModel, table=True):
    """
    public.manager  (subtipo de Users)
    """
    __tablename__ = "manager"

    id: uuid.UUID = Field(
        sa_column=Column(
            PG_UUID(as_uuid=True),
            ForeignKey("auth.users.id", ondelete="CASCADE"),
            nullable=False,
            primary_key=True,  # ✅ deja la PK aquí
        ),
    )
    organization_id: Optional[uuid.UUID] = Field(
        default=None,
        sa_column=Column(
            PG_UUID(as_uuid=True),
            ForeignKey("organization.id", ondelete="CASCADE"),
            index=True,
            nullable=True,
        ),
    )

    user: Users = Relationship(
        back_populates="manager",
        sa_relationship_kwargs={"passive_deletes": True},
    )

    organization: Optional["Organization"] = Relationship(
        back_populates="managers",
        sa_relationship_kwargs={"foreign_keys": "[Manager.organization_id]", "passive_deletes": True},
    )


class Crew(SQLModel, table=True):
    """
    public.crew  (subtipo de Users)
    """
    __tablename__ = "crew"

    id: uuid.UUID = Field(
        sa_column=Column(
            PG_UUID(as_uuid=True),
            ForeignKey("auth.users.id", ondelete="CASCADE"),
            nullable=False,
            primary_key=True,  # ✅ PK en Column
        ),
    )
    airline: Optional[str] = Field(default=None, description="Código AA, WN, DL...", index=True)

    user: Users = Relationship(
        back_populates="crew",
        sa_relationship_kwargs={"passive_deletes": True},
    )


class Driver(SQLModel, table=True):
    """
    public.driver  (subtipo de Users)
    """
    __tablename__ = "driver"

    id: uuid.UUID = Field(
        sa_column=Column(
            PG_UUID(as_uuid=True),
            ForeignKey("auth.users.id", ondelete="CASCADE"),
            nullable=False,
            primary_key=True,  # ✅ PK en Column
        ),
    )
    is_active: bool = Field(default=False, nullable=False, index=True)
    point: dict | str | None = Field(
        default=None,
        sa_column=Column(JSONB, nullable=True)
    )
    location_id: Optional[uuid.UUID] = Field(
        default=None,
        sa_column=Column(
            PG_UUID(as_uuid=True),
            ForeignKey("location.id", ondelete="CASCADE"),  # <-- CASCADE (borra drivers al borrar location)
            index=True,
            nullable=True,
        ),
    )

    user: Users = Relationship(
        back_populates="driver",
        sa_relationship_kwargs={"passive_deletes": True},
    )
    location: Optional["Location"] = Relationship(
        back_populates="drivers",
        sa_relationship_kwargs={"passive_deletes": True},
    )
    trips: List["Trip"] = Relationship(
        back_populates="driver",
        sa_relationship_kwargs={"cascade": "all, delete-orphan", "passive_deletes": True},  # <-- cascade
    )


# =========================
#  SCHEMA public : Domain
# =========================

class Organization(SQLModel, table=True):
    """
    public.organization
    """
    __tablename__ = "organization"
    """    __table_args__ = (
        UniqueConstraint("name", name="uq_organization_name"),
    )"""

    id: uuid.UUID = Field(
        default_factory=uuid.uuid4,
        primary_key=True,
        sa_column_kwargs={"server_default": text("gen_random_uuid()")},
    )
    manager_id: Optional[uuid.UUID] = Field(
        default=None,
        sa_column=Column(
            PG_UUID(as_uuid=True),
            ForeignKey("manager.id", ondelete="SET NULL"),  # <-- SET NULL para no borrar la organización
            index=True,
            nullable=True,
        ),
    )
    name: str = Field(nullable=False, index=True, unique=True)

    address: str = Field(default=None, nullable=False)
    website: str | None = Field(nullable=True, default=None)

    plan: str = Field(default="freemium", nullable=False, index=True)
    status: Optional[str] = Field(default=None, index=True)

    created_at: datetime = Field(
        default_factory=now_utc,
        sa_column=Column(DateTime(timezone=True), nullable=False, index=True, server_default=text("CURRENT_TIMESTAMP"))
    )
    updated_at: datetime = Field(
        default_factory=now_utc,
        sa_column=Column(DateTime(timezone=True), nullable=False, index=True, server_default=text("CURRENT_TIMESTAMP"))
    )

    managers: List["Manager"] = Relationship(
        back_populates="organization",
        sa_relationship_kwargs={
            "foreign_keys": "[Manager.organization_id]",
            "passive_deletes": True,
        },
    )

    primary_manager: Optional["Manager"] = Relationship(
        sa_relationship_kwargs={"foreign_keys": "[Organization.manager_id]", "passive_deletes": True},
    )

    locations: List["Location"] = Relationship(
        back_populates="organization",
        sa_relationship_kwargs={"cascade": "all, delete-orphan", "passive_deletes": True},  # <-- cascade
    )


class Location(SQLModel, table=True):
    """
    public.location
    """
    __tablename__ = "location"

    id: uuid.UUID = Field(
        default_factory=uuid.uuid4,
        primary_key=True,
        sa_column_kwargs={"server_default": text("gen_random_uuid()")},
    )
    organization_id: uuid.UUID = Field(
        sa_column=Column(
            PG_UUID(as_uuid=True),
            ForeignKey("organization.id", ondelete="CASCADE"),  # <-- CASCADE
            nullable=False,
            index=True,
        )
    )
    name: str = Field(nullable=False, index=True)
    point: dict | str | None = Field(
        default=None,
        sa_column=Column(JSONB, nullable=True)
    )

    organization: "Organization" = Relationship(
        back_populates="locations",
        sa_relationship_kwargs={"passive_deletes": True},
    )

    drivers: List["Driver"] = Relationship(
        back_populates="location",
        sa_relationship_kwargs={"cascade": "all, delete-orphan", "passive_deletes": True},  # <-- cascade
    )
    trips: List["Trip"] = Relationship(
        back_populates="location",
        sa_relationship_kwargs={"cascade": "all, delete-orphan", "passive_deletes": True},  # <-- cascade
    )


class Trip(SQLModel, table=True):
    """
    public.trip
    """
    __tablename__ = "trip"

    id: uuid.UUID = Field(
        default_factory=uuid.uuid4,
        primary_key=True,
        sa_column_kwargs={"server_default": text("gen_random_uuid()")},
    )
    assigned_driver: Optional[uuid.UUID] = Field(
        default=None,
        sa_column=Column(
            PG_UUID(as_uuid=True),
            ForeignKey("driver.id", ondelete="SET NULL"),  # <-- SET NULL al borrar driver
            index=True,
            nullable=True,
        ),
    )
    location_id: uuid.UUID = Field(
        sa_column=Column(
            PG_UUID(as_uuid=True),
            ForeignKey("location.id", ondelete="CASCADE"),  # <-- CASCADE (borra trips al borrar location)
            nullable=False,
            index=True,
        ),
    )
    pick_up_date: date = Field(
        sa_column=Column(Date(), nullable=False, index=True)
    )
    pick_up_time: time = Field(
        sa_column=Column(Time(timezone=True), nullable=False, index=True)
    )
    pick_up_location: str = Field(nullable=False)
    drop_off_location: str = Field(nullable=False)
    airline: str = Field(nullable=False, index=True)
    flight_number: str = Field(nullable=False, index=True)

    riders: int = Field(
        sa_column=Column(Integer, nullable=False)
    )

    started_at: Optional[datetime] = Field(
        default=None,
        sa_column=Column(DateTime(timezone=True), nullable=True, index=True)
    )
    picked_up_at: Optional[datetime] = Field(
        default=None,
        sa_column=Column(DateTime(timezone=True), nullable=True, index=True)
    )
    dropped_off_at: Optional[datetime] = Field(
        default=None,
        sa_column=Column(DateTime(timezone=True), nullable=True, index=True)
    )

    created_at: datetime = Field(
        default_factory=now_utc,
        sa_column=Column(DateTime(timezone=True), nullable=False, index=True, server_default=text("CURRENT_TIMESTAMP"))
    )
    updated_at: datetime = Field(
        default_factory=now_utc,
        sa_column=Column(DateTime(timezone=True), nullable=False, index=True, server_default=text("CURRENT_TIMESTAMP"))
    )

    driver: Optional["Driver"] = Relationship(
        back_populates="trips",
        sa_relationship_kwargs={"passive_deletes": True},
    )
    location: "Location" = Relationship(
        back_populates="trips",
        sa_relationship_kwargs={"passive_deletes": True},
    )


class TripHistory(SQLModel, table=True):
    """
    public.trip_history
    """
    __tablename__ = "trip_history"

    id: uuid.UUID = Field(
        default_factory=uuid.uuid4,
        primary_key=True,
        sa_column_kwargs={"server_default": text("gen_random_uuid()")},
    )
    assigned_driver: Optional[uuid.UUID] = Field(
        default=None,
        sa_column=Column(
            PG_UUID(as_uuid=True),
            ForeignKey("driver.id", ondelete="SET NULL"),  # <-- SET NULL
            index=True,
            nullable=True,
        ),
    )
    location_id: uuid.UUID = Field(
        sa_column=Column(
            PG_UUID(as_uuid=True),
            ForeignKey("location.id", ondelete="CASCADE"),  # <-- CASCADE
            nullable=False,
            index=True,
        ),
    )

    pick_up_date: date = Field(
        sa_column=Column(Date(), nullable=False, index=True)
    )
    pick_up_time: time = Field(
        sa_column=Column(Time(timezone=True), nullable=False, index=True)
    )
    pick_up_location: str = Field(nullable=False)
    drop_off_location: str = Field(nullable=False)
    airline: str = Field(nullable=False, index=True)
    flight_number: str = Field(nullable=False, index=True)

    riders: int = Field(
        sa_column=Column(Integer, nullable=False)
    )

    started_at: Optional[datetime] = Field(
        default=None,
        sa_column=Column(DateTime(timezone=True), nullable=True, index=True)
    )
    picked_up_at: Optional[datetime] = Field(
        default=None,
        sa_column=Column(DateTime(timezone=True), nullable=True, index=True)
    )
    dropped_off_at: Optional[datetime] = Field(
        default=None,
        sa_column=Column(DateTime(timezone=True), nullable=True, index=True)
    )

    created_at: datetime = Field(
        default_factory=now_utc,
        sa_column=Column(DateTime(timezone=True), nullable=False, index=True, server_default=text("CURRENT_TIMESTAMP"))
    )
    updated_at: datetime = Field(
        default_factory=now_utc,
        sa_column=Column(DateTime(timezone=True), nullable=False, index=True, server_default=text("CURRENT_TIMESTAMP"))
    )


# ======================================
#  SCHEMA public : Notification
# ======================================

class Notification(SQLModel, table=True):
    """
    public.notification
    """
    __tablename__ = "notification"

    id: uuid.UUID = Field(
        default_factory=uuid.uuid4,
        primary_key=True,
        sa_column_kwargs={"server_default": text("gen_random_uuid()")},
    )

    sender_label: Optional[str] = Field(default="system", index=True)
    sender_id: Optional[uuid.UUID] = Field(
        default=None, foreign_key="auth.users.id", index=True
    )

    recipient_id: uuid.UUID = Field(
        sa_column=Column(
            PG_UUID(as_uuid=True),
            ForeignKey("auth.users.id", ondelete="CASCADE"),  # <-- CASCADE
            nullable=False,
            index=True,
        )
    )

    link: Optional[str] = Field(default=None)
    created_at: datetime = Field(
        default_factory=now_utc,
        sa_column=Column(DateTime(timezone=True), nullable=False, index=True, server_default=text("CURRENT_TIMESTAMP"))
    )
    delivered_at: Optional[datetime] = Field(
        default=None,
        sa_column=Column(DateTime(timezone=True), nullable=True, index=True)
    )

    recipient: Users = Relationship(
        back_populates="notifications_received",
        sa_relationship_kwargs={"foreign_keys": "[Notification.recipient_id]", "passive_deletes": True},
    )


# ======================================
#  SCHEMA public : Chat & Messages
# ======================================

class Chat(SQLModel, table=True):
    """
    public.chat
    """
    __tablename__ = "chat"

    id: uuid.UUID = Field(
        default_factory=uuid.uuid4,
        primary_key=True,
        sa_column_kwargs={"server_default": text("gen_random_uuid()")},
    )
    created_at: datetime = Field(
        default_factory=now_utc,
        sa_column=Column(DateTime(timezone=True), nullable=False, index=True, server_default=text("CURRENT_TIMESTAMP"))
    )

    participants: List["ChatParticipant"] = Relationship(
        back_populates="chat",
        sa_relationship_kwargs={"cascade": "all, delete-orphan", "passive_deletes": True},  # <-- cascade
    )
    messages: List["Message"] = Relationship(
        back_populates="chat",
        sa_relationship_kwargs={"cascade": "all, delete-orphan", "passive_deletes": True},  # <-- cascade
    )


class ChatParticipant(SQLModel, table=True):
    """
    public.chat_participant
    """
    __tablename__ = "chat_participant"
    __table_args__ = (UniqueConstraint("chat_id", "user_id", name="uq_chat_participant_unique"),)

    id: uuid.UUID = Field(
        default_factory=uuid.uuid4,
        primary_key=True,
        sa_column_kwargs={"server_default": text("gen_random_uuid()")},
    )
    chat_id: uuid.UUID = Field(
        sa_column=Column(
            PG_UUID(as_uuid=True),
            ForeignKey("chat.id", ondelete="CASCADE"),  # <-- CASCADE
            nullable=False,
            index=True,
        )
    )
    user_id: uuid.UUID = Field(
        sa_column=Column(
            PG_UUID(as_uuid=True),
            ForeignKey("auth.users.id", ondelete="CASCADE"),  # <-- CASCADE
            nullable=False,
            index=True,
        )
    )
    joined_at: datetime = Field(
        default_factory=now_utc,
        sa_column=Column(DateTime(timezone=True), nullable=False, index=True, server_default=text("CURRENT_TIMESTAMP"))
    )

    chat: Chat = Relationship(
        back_populates="participants",
        sa_relationship_kwargs={"passive_deletes": True},
    )
    user: Users = Relationship(
        sa_relationship_kwargs={"passive_deletes": True},
    )


class Message(SQLModel, table=True):
    """
    public.message
    """
    __tablename__ = "message"

    id: uuid.UUID = Field(
        default_factory=uuid.uuid4,
        primary_key=True,
        sa_column_kwargs={"server_default": text("gen_random_uuid()")},
    )
    chat_id: uuid.UUID = Field(
        sa_column=Column(
            PG_UUID(as_uuid=True),
            ForeignKey("chat.id", ondelete="CASCADE"),  # <-- CASCADE
            nullable=False,
            index=True,
        )
    )
    sender_id: uuid.UUID = Field(
        sa_column=Column(
            PG_UUID(as_uuid=True),
            ForeignKey("auth.users.id", ondelete="CASCADE"),  # <-- CASCADE
            nullable=False,
            index=True,
        )
    )
    recipient_id: Optional[uuid.UUID] = Field(
        default=None,
        sa_column=Column(
            PG_UUID(as_uuid=True),
            ForeignKey("auth.users.id", ondelete="CASCADE"),  # <-- CASCADE
            nullable=True,
            index=True,
        )
    )

    content: str = Field(nullable=False)
    created_at: datetime = Field(
        default_factory=now_utc,
        sa_column=Column(DateTime(timezone=True), nullable=False, index=True, server_default=text("CURRENT_TIMESTAMP"))
    )

    chat: Chat = Relationship(
        back_populates="messages",
        sa_relationship_kwargs={"passive_deletes": True},
    )
    sender: Users = Relationship(
        back_populates="sent_messages",
        sa_relationship_kwargs={"foreign_keys": "[Message.sender_id]", "passive_deletes": True},
    )
    recipient: Optional[Users] = Relationship(
        back_populates="received_messages",
        sa_relationship_kwargs={"foreign_keys": "[Message.recipient_id]", "passive_deletes": True},
    )


# ======================================
#  SCHEMA auth : RefreshToken
# ======================================

class Token(SQLModel, table=True):
    """
    auth.token
    """
    __tablename__ = "token"
    __table_args__ = (
        UniqueConstraint("token_hash", name="uq_token_hash"),
        AUTH_TABLE_ARGS,
    )

    id: uuid.UUID = Field(
        default_factory=uuid.uuid4,
        primary_key=True,
        sa_column_kwargs={"server_default": text("gen_random_uuid()")},
    )
    user_id: uuid.UUID = Field(
        sa_column=Column(
            PG_UUID(as_uuid=True),
            ForeignKey("auth.users.id", ondelete="CASCADE"),  # <-- CASCADE
            nullable=False,
            index=True,
        )
    )
    token_hash: str = Field(nullable=False)
    token_type: str = Field(nullable=False)
    expires_at: datetime = Field(
        sa_column=Column(DateTime(timezone=True), nullable=False, index=True)
    )
    revoked: bool = Field(default=False, nullable=False, index=True)
    created_at: datetime = Field(
        default_factory=now_utc,
        sa_column=Column(DateTime(timezone=True), nullable=False, index=True, server_default=text("CURRENT_TIMESTAMP"))
    )

    user: Users = Relationship(
        back_populates="refresh_tokens",
        sa_relationship_kwargs={"foreign_keys": "[Token.user_id]", "passive_deletes": True},
    )

    


class Airport(SQLModel, table=True):
    __tablename__ = "airport"
    __table_args__ = (
        UniqueConstraint("code", name="uq_airport_code"),
        CheckConstraint("latitude BETWEEN -90 AND 90", name="ck_airport_lat"),
        CheckConstraint("longitude BETWEEN -180 AND 180", name="ck_airport_lon"),
        Index("ix_airport_country_zone", "country_code", "zone_code"),
    )

    id: uuid.UUID = Field(
        default_factory=uuid.uuid4,
        primary_key=True,
        sa_column_kwargs={"server_default": text("gen_random_uuid()")},
    )
    code: str = Field(
        sa_column=Column(String(10), nullable=False, index=True)
    ) 
    name: str = Field(
        sa_column=Column(String(150), nullable=False)
    ) 
    latitude: float = Field(
        sa_column=Column(Float, nullable=False)
    ) 
    longitude: float = Field(
        sa_column=Column(Float, nullable=False)
    ) 
    country_code: str = Field(
        sa_column=Column(String(2), nullable=False, index=True)
    )
    zone_code: str = Field(
        sa_column=Column(String(4), nullable=False, index=True)
    )